### PR TITLE
Update Range Check regexp

### LINKED ISSUE #235: RegexpWarnings in Goland
just to let you know Jetbrains Goland raises serveral RegExp warnings in range.go, which are causing force commits with changed code

```
Warning:(83, 49) Redundant character escape '\@' in RegExp
Warning:(83, 53) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(83, 64) Redundant character escape '\.' in RegExp
Warning:(83, 73) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(83, 84) Redundant character escape '\.' in RegExp
Warning:(83, 98) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(83, 109) Redundant character escape '\.' in RegExp
Warning:(83, 118) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(83, 129) Redundant character escape '\.' in RegExp
Warning:(84, 44) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(84, 55) Redundant character escape '\.' in RegExp
Warning:(84, 64) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(84, 75) Redundant character escape '\.' in RegExp
Warning:(85, 37) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(85, 48) Redundant character escape '\.' in RegExp
Warning:(85, 57) Unnecessary non-capturing group '(?:[-+]?[\d\.]+)'
Warning:(85, 68) Redundant character escape '\.' in RegExp
```

### PR DESCRIPTION
**Pull request by Tommi2Day**
fix #235

### CODE REVIEW

**Comment by atc0005** [comment]
@Tommi2Day 

Thanks for submitting this PR.

@infraweavers

As noted on GH-235, this set of changes comes from linting recommendations provided by the GoLand IDE. 

Two warnings are present (repeated as applicable):

- unnecessary non-capturing group
- redundant character escape

Do you have any concerns with applying the GoLand recommendations?

**Comment by atc0005** [comment]
@Tommi2Day We can give this until early next week to give @infraweavers a chance to respond and plan to merge either way then. 

If there are any issues that we aren't catching we can always back out the change later and document the specific reasoning behind a need for the earlier regex formats.

**Comment by atc0005** [comment]
@Tommi2Day Since we've not heard any objections/corrections from @infraweavers I believe we can proceed with merging these changes.

Are you willing to rebase your PR branch? If not I can do so before the merge.

Thanks.

**Comment by Tommi2Day** [comment]
branch has been rebased with current master

**Pull request merged**
